databases:
  - name: racket-fusion
    databaseName: racket-fusion
    user: swswiss
    plan: free

services:
  - type: web
    name: racket-fusion
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "./bin/rails server"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: racket-fusion
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
