User.destroy_all
User.create( email: "silviu69@yahoo.com", username: "silviu saizesi0", display_name: "Silviu saizesi0", image_profile: "astronaut", admin: nil, points: 0, rank: nil, phone: "24243353434", level: "Expert", date_of_birth: nil, encrypted_password: "salutsalut")
User.create( email: "silviu1@yahoo.com", username: "Laura", display_name: "Laura", image_profile: "tennis2", admin: nil, points: 31, rank: nil, phone: "324535654234", level: "Medium", date_of_birth: nil, encrypted_password: "salutsalut")
User.create( email: "novak1@yahoo.com", username: "novak", display_name: "novak", image_profile: "gamer", admin: nil, points: 20, rank: nil, phone: "2343242333", level: "Medium", date_of_birth: nil, encrypted_password: "salutsalut")
User.create( email: "silviu3@yahoo.com", username: "cludiud humureanu", display_name: "Cludiud humureanu", image_profile: nil, admin: nil, points: 40, rank: nil, phone: "324535654234", level: "Medium", date_of_birth: nil, encrypted_password: "salutsalut")
User.create( email: "nadal@yahoo.com", username: "nadal", display_name: "Nadal", image_profile: "astronaut", admin: nil, points: 40, rank: nil, phone: "3444444444", level: "Medium", date_of_birth: nil, encrypted_password: "salutsalut")
User.create( email: "constantin@yahoo.com", username: "costica", display_name: "costicel", image_profile: "man", admin: nil, points: 28, rank: nil, phone: "324535654234", level: "Medium", date_of_birth: nil, encrypted_password: "salutsalut")
User.create( email: "silviu4@yahoo.com", username: "roger federer", display_name: "Roger federer", image_profile: "astronaut", admin: nil, points: 0, rank: nil, phone: "324535654234", level: "Medium", date_of_birth: nil, encrypted_password: "salutsalut")
User.create( email: "roger_novak@yahoo.com", username: "dscsdc", display_name: "Dscsdc", image_profile: nil, admin: nil, points: 0, rank: nil, phone: "324535654234", level: "Medium", date_of_birth: nil, encrypted_password: "salutsalut")
User.create( email: "omg@yahoo.com", username: "viorel", display_name: "Viorel", image_profile: "man", admin: nil, points: 0, rank: nil, phone: "324535654234", level: "Medium", date_of_birth: nil, encrypted_password: 'salutsalut')
User.create( email: "alex@yahoo.com", username: "alex1", display_name: "alex1", image_profile: "man", admin: nil, points: 20, rank: nil, phone: "3243254325", level: "Medium", date_of_birth: nil, encrypted_password: 'salutsalut')


User.create( email: "silviu@yahoo.com", username: "Silviu", display_name: "Silviuss", image_profile: "tennis1", admin: true, points: 84, rank: nil, phone: "324535651110", level: "Medium", date_of_birth: "1993-10-20 00:00:00.000000000 +0000", encrypted_password: 'salutsalut')